<?php require DIR_PATH . DS . 'includes' . DS . 'top_content_inc.php';?>

<section id="top-section">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="top-main-image">
                    <h1 class="top-main-text">Podziel się swoją niezwykłą twórczością</h1>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="main-page-section" id="middle-text-section">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <p>Your view to miejsce, w którym każdy może udostępnić innym swoją niezwykłą fotografię, grafikę lub rysunek.
                    Tutaj Ty jesteś artystą, a inni użytkownicy oceniają Twoją pracę.
                    Im większe oceny  będziesz  otrzymywać, tym wyżej w rankingu znajdzie  się Twoja  twórczość.
                    Poznaj możliwości Your view i stań się popularny dzięki swoim umiejętnością manualnym lub fotograficznym!</p>
            </div>
        </div>
    </div>
</section>
<section class="main-page-section" id="top-rated-section">
    <div class="container">
        <div class="row">
            <div class="col-lg-4">
                <div class="main-page-top-rated">
                    <div class="main-page-top-rated-img">
                        <img src="http://localhost/your-view/public/img/sample1.jpg" alt="">
                    </div>
                    <div class="main-page-user-info">
                        <div class="user-avatar">
                            <img src="http://localhost/your-view/public/img/user-sample-avatar1.jpg" alt="">
                        </div>
                        <span class="main-page-user-name">Bartek</span>
                        <div class="art-grade">
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="main-page-top-rated">
                    <div class="main-page-top-rated-img">
                        <img src="http://localhost/your-view/public/img/sample1.jpg" alt="">
                    </div>
                    <div class="main-page-user-info">
                        <div class="user-avatar">
                            <img src="http://localhost/your-view/public/img/user-sample-avatar1.jpg" alt="">
                        </div>
                        <span class="main-page-user-name">Bartek</span>
                        <div class="art-grade">
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="main-page-top-rated">
                    <div class="main-page-top-rated-img">
                        <img src="http://localhost/your-view/public/img/sample1.jpg" alt="">
                    </div>
                    <div class="main-page-user-info">
                        <div class="user-avatar">
                            <img src="http://localhost/your-view/public/img/user-sample-avatar1.jpg" alt="">
                        </div>
                        <span class="main-page-user-name">Bartek</span>
                        <div class="art-grade">
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <hr>
        </div>
    </div>
</div>
<section class="main-page-section" id="bottom-section">
    <div class="container">
        <div class="row">
            <div class="col-lg-4">
                <div class="main-page-info">
                    <i class="fas fa-users"></i>
                    <p>Dołącz do wspaniałej społeczności</p>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="main-page-info">
                    <i class="fas fa-images"></i>
                    <p>Podziel się swoją twórczością</p>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="main-page-info">
                    <i class="fas fa-comment-medical"></i>
                    <p>Oceniaj i komentuj prace innych</p>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="justify-paragraph">
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                        Aliquid asperiores blanditiis fuga inventore ipsum nemo nihil nostrum recusandae sunt totam!
                        Ab beatae deserunt dolorem ex, ipsam nihil quae quibusdam voluptatibus quibusdam voluptatibu.</p>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                        Aliquid asperiores blanditiis fuga inventore ipsum nemo nihil nostrum recusandae sunt totam!
                        Ab beatae deserunt dolorem ex, ipsam nihil quae quibusdam voluptatibus?</p>
                </div>
            </div>
        </div>
    </div>
</section>
<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <hr>
        </div>
    </div>
</div>

<?php require DIR_PATH . DS . 'includes' . DS . 'bottom_content_inc.php';
