<?php session_start();
if (isset($_SESSION['id'])) header('Location: http://localhost/your-view/');
require DIR_PATH . DS . 'includes' . DS . 'top_content_inc.php';?>


<section id="login-section">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="login-panel">
                    <h1>Zaloguj się</h1>
                    <form action="http://localhost/your-view/app/scripts/login.php" method="post">
                        <input name="login" type="text" placeholder="&#xF007; Wpisz swój login"><br>
                        <input name="password" type="password" placeholder="&#xf023; Wpisz swoje hasło"><br>
                        <input name="submit" type="submit" value="Zaloguj">
                        <p class="forgot-password">Zapomniałeś hasła?</p>
                        <div class="login-with-socials">
                            <p>Zaloguj się za pomocą Facebooka</p>
                            <i class="fab fa-facebook"></i>
                        </div>
                        <div class="no-account">
                            <p>Nie posiadasz jeszcze konta?</p>
                            <p>Zarejestruj się!</p>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>



<?php require DIR_PATH . DS . 'includes' . DS . 'bottom_content_inc.php';