<?php
require DIR_PATH . DS . 'includes' . DS . 'top_content_inc.php';
require_once DIR_PATH . DS . 'config' . DS . 'defines.php';
if (!USER_LOGGED_IN)
    header('Location: ' . HOST);
?>

<section id="user-settings">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="user-settings-container">
                    <h1>Ustawienia konta</h1>
                    <div class="user-avatar-settings mt-5">
                        <div class="user-avatar-over">
                            <img id="user-avatar" src="<?= HOST . 'public/img/user-sample-avatar1.jpg' ?>" alt="">
                            <div class="user-avatar-edit" title="Edytuj swoje zdjęcie">
                                <i class="far fa-image"></i>
                            </div>
                            <input type="file" id="imgupload" style="display:none"/>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<?php require DIR_PATH . DS . 'includes' . DS . 'bottom_content_inc.php';