<?php
require_once DIR_PATH . DS . 'includes' . DS . 'cms' . DS . 'cms_top_content_inc.phtml';
require_once DIR_PATH . DS . 'model' . DS . 'cms' . DS . 'Seo.php';

$seo = new Seo();
$seo->getSeoSettings();


?>
    <h1 class="mb-4">Ustawienia SEO</h1>
    <form action="<?= HOST ?>app/scripts/cms/seo/update.php" method="post">
        <div class="cms-head-with-input">
            <p class="cms-input-head">Domyślny meta-title</p>
            <input type="text" name="def_meta_title" class="cms-input" value="<?= $seo->getDefaultMetaTitle() ?>">
        </div>
        <input type="submit" value="Zapisz" class="blue-btn mt-2 pl-2 pr-2"">
    </form>
<?php
require_once DIR_PATH . DS . 'includes' . DS . 'cms' . DS . 'cms_bottom_content_inc.phtml';
