<?php require DIR_PATH . DS . 'includes' . DS . 'top_content_inc.php';?>

<section id="admin-page" class="mt-5">
    <ul class="cms-menu">
        <li><i class="far fa-file-alt"></i>Strony</li>
        <li><i class="fas fa-bars"></i><a href="<?=HOST?>admin/cms-menu">Menu</a></li>
        <li><i class="fas fa-tools"></i>Ustawienia</li>
        <ul class="cms-submenu">
            <li>Nagłówek</li>
            <li>Stopka</li>
            <li>SEO</li>
        </ul>
    </ul>
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="cms-content">