<?php
require_once DIR_PATH . DS . 'includes' . DS . 'cms' . DS . 'cms_top_content_inc.phtml';
require_once DIR_PATH . DS . 'model' . DS . 'cms' . DS . 'Page.php';

$page = new Page();
$pages = $page->getAllPages();
?>
<h1 class="mb-4">Lista utworzonych stron</h1>
<ul class="no-list-style">
    <?php if (empty($pages)): ?>
        <p>Brak utworzonych stron</p>
    <?php endif; ?>
    <?php foreach ($pages as $page): ?>
        <a href="<?= HOST ?>admin/cms-edit-page?id=<?= $page->getId() ?>"><li class="cms-created-page"><?= $page->getName() ?></li></a>
    <?php endforeach; ?>
</ul>

<?php
require_once DIR_PATH . DS . 'includes' . DS . 'cms' . DS . 'cms_bottom_content_inc.phtml';
