<?php
require_once (dirname(__FILE__).'/../model/cms/Page.php');
require_once (dirname(__FILE__).'/../model/cms/Seo.php');

$uri = $_SERVER['REQUEST_URI'];

$uri = explode('/', $uri);

$page = new Page();
$page->getPageByUri($uri[2]);

$seo = new Seo();
$seo->getSeoSettings();
$seo->replaceSeoVariables($page->getName());

if (empty($page->getMetaTitle())) {
    $page->setMetaTitle($seo->getDefaultMetaTitle());
}

?>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <script src="https://kit.fontawesome.com/752157b47f.js" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap&subset=latin-ext" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700&display=swap&subset=latin-ext" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="<?= HOST ?>public/css/main.css">
    <link rel="stylesheet" href="<?= HOST ?>public/css/croppie.css">
    <script src="https://cdn.tiny.cloud/1/s6dh7kj3il7jcgsrvqf7lg7aq7icpg4kvi27uokqn8hj1yv1/tinymce/5/tinymce.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="<?= HOST ?>public/js/main.js"></script>
    <title><?= $page->getMetaTitle() ?></title>
    <meta name="description" content="<?= $page->getMetaDesc() ?>">
    <meta name="robots" content="<?= $page->getMetaRobots() ?>">
</head>